name: Alerta no Discord
on:
   workflow_run:
       workflows:
           - "Continuous Integration"
           - "CodeQL"

       types:
           - completed

# Princípio do menor privilégio
permissions: {}

jobs:
    message:
        name: Notificar no Discord
        runs-on: ubuntu-latest
        
        steps:
        
          # CI - RUFF + PYTEST
          - name: Aviso CI bem-sucedida
            if: >
                ${{ github.event.workflow_run.path == '.github/workflows/ci.yml'
                && github.event.workflow_run.conclusion == 'success' }}
            uses: tsickert/discord-webhook@v7.0.0
            with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
                content: ":-) CI concluída com sucesso! Ruff e Pytest passaram."
                 
          - name: Aviso CI malsucedida
            if: >
                 ${{ github.event.workflow_run.path == '.github/workflows/ci.yml'
                 && github.event.workflow_run.conclusion == 'failure' }}
            uses: tsickert/discord-webhook@v7.0.0
            with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
                content: ":-( A CI apresentou falha no Ruff ou no Pytest."
                
          # CODEQL
          - name: Aviso CodeQL bem-sucedido!
            if: >
                ${{ github.event.workflow_run.path == 'dynamic/github-code-scanning/codeql'
                && github.event.workflow_run.conclusion == 'success' }}
            uses: tsickert/discord-webhook@v7.0.0
            with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
                content: ":-) CodeQL concluído com sucesso!"
                
          - name: Aviso CodeQL malsucedido
            if: >
                ${{ github.event.workflow_run.path == 'dynamic/github-code-scanning/codeql'
                && github.event.workflow_run.conclusion == 'failure' }}
            uses: tsickert/discord-webhook@v7.0.0
            with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
                content: ":-( CodeQL apresentou falha!"
